CREATE TABLE IF NOT EXISTS PUBLIC."user" (
	ID CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	FIRST_NAME CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	LAST_NAME CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	EMAIL CHARACTER VARYING[] COLLATE PG_CATALOG."default",
	PASSWORD CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CONTACT CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	ROLE CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	LOCATION CHARACTER VARYING[] COLLATE PG_CATALOG."default",
	CREATED_AT DATE NOT NULL DEFAULT CURRENT_DATE,
	UPDATED_AT DATE NOT NULL DEFAULT CURRENT_DATE,
	CONSTRAINT USER_PKEY PRIMARY KEY (ID)
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."fault" (
	ID CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	DESCRIPTION CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	STATUS CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	LOCATION CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CREATED_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	UPDATE_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	ID_USER CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT FAULT_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_USER FOREIGN KEY (ID_USER) REFERENCES PUBLIC.USER (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."chat_session" (
	ID CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CREATED_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	UPDATED_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	ID_USER CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	ID_FAULT CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT CHAT_SESSION_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_USER FOREIGN KEY (ID_USER) REFERENCES PUBLIC.USER (ID) ON DELETE CASCADE,
	CONSTRAINT ID_FAULT FOREIGN KEY (ID_FAULT) REFERENCES PUBLIC.FAULT (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."asset" (
	ID CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	TYPE CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	LOCATION CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT ASSET_PKEY PRIMARY KEY (ID)
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."message" (
	ID CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	MESSAGE CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CREATED_DATE DATE DEFAULT CURRENT_DATE,
	UPDATED_DATE DATE DEFAULT CURRENT_DATE,
	ID_CHAT_SESSION CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT MESSAGE_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_CHAT_SESSION FOREIGN KEY (ID_CHAT_SESSION) REFERENCES PUBLIC.CHAT_SESSION (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."answer" (
	ID CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	ANSWER CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	SEND_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
	ID_MESSAGE CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	ID_CHAT_SESSION CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT ANSWER_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_MESSAGE FOREIGN KEY (ID_MESSAGE) REFERENCES PUBLIC.MESSAGE (ID) ON DELETE CASCADE,
	CONSTRAINT ID_CHAT_SESSION FOREIGN KEY (ID_CHAT_SESSION) REFERENCES PUBLIC.CHAT_SESSION (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."tool" (
	ID CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	NAME CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	STATUS CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT TOOL_PKEY PRIMARY KEY (ID)
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."ticket" (
	ID CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	PRIORITY CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	STATUS CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	ID_USER CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	ID_FAULT CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT TICKET_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_USER FOREIGN KEY (ID_USER) REFERENCES PUBLIC.USER (ID) ON DELETE CASCADE,
	CONSTRAINT ID_FAULT FOREIGN KEY (ID_FAULT) REFERENCES PUBLIC.FAULT (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."request" (
	ID CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	QUANTITY CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	REQUEST_DATE DATE NOT NULL,
	HANDED_DATE DATE NOT NULL,
	RETURN_DATE DATE NOT NULL,
	ID_TICKET CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	ID_TOOL CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT REQUEST_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_TICKET FOREIGN KEY (ID_TICKET) REFERENCES PUBLIC.TICKET (ID) ON DELETE CASCADE,
	CONSTRAINT ID_TOOL FOREIGN KEY (ID_TOOL) REFERENCES PUBLIC.TOOL (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."geocordinate" (
	ID CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	LATTITUDE BIGINT NOT NULL,
	LONGITUDE BIGINT NOT NULL,
	ADDRESS CHARACTER VARYING[] COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT GEOCORDINATE_PKEY PRIMARY KEY (ID)
) TABLESPACE PG_DEFAULT;