CREATE TYPE ROLE AS ENUM ('CLIENT', 'FIELD_AGENT', 'ADMIN');
CREATE TYPE STATUS AS ENUM ('ACTIVE', 'PENDING', 'COMPLETED');
CREATE TYPE LOCATION AS
(
	longitude numeric,
	lattitude numeric,
	address VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS PUBLIC."user" (
	ID VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	FIRST_NAME VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	LAST_NAME VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	EMAIL VARCHAR(36) COLLATE PG_CATALOG."default",
	PASSWORD VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	CONTACT VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	ROLE ROLE COLLATE PG_CATALOG."default" NOT NULL,
	LOCATION LOCATION,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
	CONSTRAINT USER_PKEY PRIMARY KEY (ID)
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."refresh_token" (
	ID VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	TOKEN VARCHAR(200) COLLATE PG_CATALOG."default" NOT NULL,
	EXPIRES_AT TIMESTAMP NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
	CONSTRAINT REFRESH_TOKEN_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_USER FOREIGN KEY (ID) REFERENCES PUBLIC.USER (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."fault" (
	ID VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	DESCRIPTION VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	STATUS STATUS COLLATE PG_CATALOG."default" NOT NULL,
	LOCATION LOCATION,
	CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
	UPDATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
	ID_USER VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT FAULT_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_USER FOREIGN KEY (ID_USER) REFERENCES PUBLIC.USER (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."chat_session" (
	ID VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
	UPDATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
	ID_USER VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	ID_FAULT VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT CHAT_SESSION_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_USER FOREIGN KEY (ID_USER) REFERENCES PUBLIC.USER (ID) ON DELETE CASCADE,
	CONSTRAINT ID_FAULT FOREIGN KEY (ID_FAULT) REFERENCES PUBLIC.FAULT (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."asset" (
	ID VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	TYPE VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	LOCATION LOCATION COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT ASSET_PKEY PRIMARY KEY (ID)
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."message" (
	ID VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	MESSAGE VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	CREATED_DATE DATE DEFAULT CURRENT_DATE,
	UPDATED_DATE DATE DEFAULT CURRENT_DATE,
	ID_CHAT_SESSION VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT MESSAGE_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_CHAT_SESSION FOREIGN KEY (ID_CHAT_SESSION) REFERENCES PUBLIC.CHAT_SESSION (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."answer" (
	ID VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	ANSWER VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	SEND_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
	ID_MESSAGE VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	ID_CHAT_SESSION VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT ANSWER_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_MESSAGE FOREIGN KEY (ID_MESSAGE) REFERENCES PUBLIC.MESSAGE (ID) ON DELETE CASCADE,
	CONSTRAINT ID_CHAT_SESSION FOREIGN KEY (ID_CHAT_SESSION) REFERENCES PUBLIC.CHAT_SESSION (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."tool" (
	ID VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	NAME VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT TOOL_PKEY PRIMARY KEY (ID)
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."ticket" (
	ID VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	PRIORITY VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	STATUS VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	ID_USER VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	ID_FAULT VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT TICKET_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_USER FOREIGN KEY (ID_USER) REFERENCES PUBLIC.USER (ID) ON DELETE CASCADE,
	CONSTRAINT ID_FAULT FOREIGN KEY (ID_FAULT) REFERENCES PUBLIC.FAULT (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."request" (
	ID VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	QUANTITY VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	REQUEST_DATE TIMESTAMP NOT NULL,
	HANDED_DATE TIMESTAMP NOT NULL,
	RETURN_DATE TIMESTAMP NOT NULL,
	STATUS VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	ID_TICKET VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	ID_TOOL VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT REQUEST_PKEY PRIMARY KEY (ID),
	CONSTRAINT ID_TICKET FOREIGN KEY (ID_TICKET) REFERENCES PUBLIC.TICKET (ID) ON DELETE CASCADE,
	CONSTRAINT ID_TOOL FOREIGN KEY (ID_TOOL) REFERENCES PUBLIC.TOOL (ID) ON DELETE CASCADE
) TABLESPACE PG_DEFAULT;

CREATE TABLE IF NOT EXISTS PUBLIC."geocordinate" (
	ID VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	LATTITUDE BIGINT NOT NULL,
	LONGITUDE BIGINT NOT NULL,
	ADDRESS VARCHAR(36) COLLATE PG_CATALOG."default" NOT NULL,
	CONSTRAINT GEOCORDINATE_PKEY PRIMARY KEY (ID)
) TABLESPACE PG_DEFAULT;